### ISSUE TITLE
What is Peripheral::request supposed to return?

### ISSUE THREAD

**Issue by qwandor** [deviceplug/btleplug#104]
GATT defines two ways of writing to a characteristic: write (ATT write request/response), and write without response (ATT write command). The 'response' in the in the write feature is just an acknowledgement that the write request was successful (or that it failed), and as far as I can see doesn't actually contain any data.

With that in mind, what is the `btleplug::api::Peripheral::request` supposed to return? Looking at the code, `request` isn't implemented at all for `winrtble`, and in the `corebluetooth` implementation just returns a copy of the value which was written. In the `bluez` implementation it seems to return something from BlueZ, but I can't figure out what.

It seems to me that this method should be changed to just return `Result<()>` like `Peripheral::command`. Or potentially, they could be combined into a single method, as the choice between using write or write without response is usually a matter of what the device supports rather than a conscious choice made by the application.

**Comment by qdot** [comment]
Fixed in v0.6.0 by @qwandor. Yay for answering your own question. :)
