### ISSUE TITLE
AdapterManager::update_peripheral does nothing

### ISSUE THREAD

**Issue by qwandor** [deviceplug/btleplug#117]
**Describe the bug**
It appears that `AdapterManager::update_peripheral` currently does nothing. It looks up a peripheral, clones its properties a bunch of times, sets some property on each clone of the properties and then drops it.

**Expected behavior**
I would expect this method to have some effect on the state of the `AdapterManager`.

**Actual behavior**
Nothing.

**Additional context**
I'm trying to move the API to aysnc in #114.

I'd be interested to discuss the reasoning behind the `AdapterManager` in the first place, and whether it's really a good idea to cache state about the system like this, rather than calling up to the system APIs to get information about peripherals.

**Comment by qdot** [comment]
I think this got pretty much figured out with the discrepancies of BlueZ versus Everyone Else, so we're all good now. Closing.
