### ISSUE TITLE
Link to documentation

### ISSUE THREAD

**Issue by piegamesde** [deviceplug/btleplug#132]
There are hosted docs for this crate [on docs.rs](https://docs.rs/btleplug/0.7.1/btleplug/), but neither the README nor the crates.io home page link to them for some reason.

**Comment by qwandor** [comment]
crates.io does have a link in the usual place, but adding it to the README is a good idea.

**Comment by piegamesde** [comment]
> crates.io does have a link in the usual place

Weird. It doesn't for me
![image](https://user-images.githubusercontent.com/14054505/109881558-c9e3c780-7c78-11eb-886d-83ed2ce33506.png)

**Comment by qwandor** [comment]
Huh, that is indeed weird. It shows it for me on the right, between 'Install' and 'Repository', whether or not I'm logged in. Does it work for other crates?

**Comment by piegamesde** [comment]
> Does it work for other crates?

On some yes, on other not. https://crates.io/crates/ash has a doc link for me, https://crates.io/crates/blurz not.

**Comment by qdot** [comment]
Docs link is in our README now, closing.
