### ISSUE TITLE
Set up Azure Pipelines CI

### ISSUE THREAD

**Issue by qdot** [deviceplug/btleplug#16]
It's where I run all of my builds currently, works well for cross platform, etc.

**Comment by mfiumara** [comment]
Is there a reason to use zure pipelines over github actions? Since the code is hosted on github might make sense.

**Comment by qdot** [comment]
@mfiumara Mostly that I already have deep experience with Azure Pipelines and should be able to bring over my already built configs.

**Comment by mfiumara** [comment]
Alright makes sense, I did some azure pipelines myself and it's a very nice CI tool. If you want to check how github actions look like I linked a PR.

**Comment by qdot** [comment]
Thanks for the PR, but went with Azure anyways.
