### ISSUE TITLE
Linux + ELM327 BT (Serial bluetooth)

### ISSUE THREAD

**Issue by rnd-ash** [deviceplug/btleplug#160]
**Describe the bug**
When connecting a serial BT device such as ELM327, the library fails to connect the device (Or read characteristics) with
```
BTError(Other("org.bluez.Error.NotAvailable: Operation currently not available"))
```
This is with version 0.7.2.

**Expected behavior**
The device should connect

**Actual behavior**
The device does not connect

**Comment by qdot** [comment]
Serial Bluetooth is Bluetooth Classic. This library is Bluetooth LE only, and there are no plans on extending support to BT2/RFCOMM/etc. Might just try regular a serial port library.
