### ISSUE TITLE
Windows' `Peripheral::discover_characteristics` does not update list accessible through `Peripheral::characteristics`

### ISSUE THREAD

**Issue by the6p4c** [deviceplug/btleplug#170]
**Describe the bug**
After calling `Peripheral::discover_characteristics` on a device, the list of characteristics returned by `Peripheral::characteristics` (i.e. the `characteristics` field in the `Peripheral` struct in [`src/winrtble/peripheral.rs`](https://github.com/deviceplug/btleplug/blob/33e5acd06d17235bb932fa33e3fb6973c57905bd/src/winrtble/peripheral.rs#L45)) does not update. In fact, there don't appear to be any modifications made to the field, ever.

The list returned by `Peripheral::discover_characteristics`, however, does contain the correct characteristics.

This results in the README example displaying no characteristics on Windows.

**Expected behavior**
The list of characteristics returned is updated after they are discovered.

**Actual behavior**
The list of characteristics returned is not updated, and remains empty.

**Comment by qdot** [comment]
This should be fixed in both v0.7.3 and v0.8, closing.
