### ISSUE TITLE
Remove DeviceLost event, change macOS to emit DeviceDisconnected

### ISSUE THREAD

**Issue by qdot** [deviceplug/btleplug#176]
**Feature Description**

DeviceLost is currently only fired by macOS. BlueZ had it but lost it after @NZSmartie's patches got written over, and I'm not sure if it's even a thing on Windows so we might have to do our own timing there to emulate it.

**Comment by qwandor** [comment]
It looks like the MacOS implementation is firing `DeviceLost` in response to `on_peripheral_disconnect`, which should be `DeviceDisconnected`. What is `DeviceLost` supposed to mean, actually?

**Comment by qdot** [comment]
Oh. Well. That's a completely different bug then heh.

I just went back and looked at rumble, and they never implemented DeviceLost, just had it in their enum, with no explanation. So, gonna change this bug to "Remove DeviceLost and change macOS to DeviceDisconnected"

**Comment by qwandor** [comment]
Fixed in dev.
