### ISSUE TITLE
Sometimes names aren't found

### ISSUE THREAD

**Issue by joonazan** [deviceplug/btleplug#20]
At first this library worked for me, but after a while it stopped finding the name of my device.

I don't know how BLE works, but I suspect the missing name might be because of the ordering of broadcasts. `sudo hcitool lescan` shows

```
3C:71:BF:CB:1E:42 (unknown)
3C:71:BF:CB:1E:42 position sensor
```

**Comment by qdot** [comment]
Ok, this looks like the same problem happening in #20, so I'm gonna dupe this one and discuss it over there.
