### ISSUE TITLE
Windows v0.30 will break UWP portion of library

### ISSUE THREAD

**Issue by qdot** [deviceplug/btleplug#231]
More a heads up than anything. windows v0.29 crate will break a bunch of windows stuff. A lot of types no longer implement Debug, and the new generator doesn't seem to bring in Send on some types, which is a problem when they're wrapped in IAsyncOperation. I've filed a couple of bugs over in windows-rs but I doubt there will be any movement until the new year. No rush to update the windows crate either, just something to be aware of.

**Comment by qdot** [comment]
Ok, updating this for v0.30, which came out a few days ago. Most of the original breakage is gone thanks to the reimplementation of Debug, we're now down to a single struct that should be an enum (BluetoothAddressType). I'll file on this and we'll see what happens, but if we get stuck we can always make our own version.

**Comment by qdot** [comment]
Filed at https://github.com/microsoft/windows-rs/issues/1437

**Comment by hansmbakker** [comment]
Maybe this issue can be closed because of the fix in https://github.com/microsoft/windows-rs/issues/1437

**Comment by qdot** [comment]
LAnded a while ago.
