### ISSUE TITLE
Disconnect is not implemented for corebluetooth

### ISSUE THREAD

**Issue by Yohannfra** [deviceplug/btleplug#262]
**Describe the bug**
In corebluetooth the implementation of the disconnect function is 

```rust
    async fn disconnect(&self) -> Result<()> {
        // TODO
        Ok(())
    }
```

**Expected behavior**
An actual disconnection

**Actual behavior**
Nothing

Thanks you for this library :)

**Comment by qdot** [comment]
Well that's some timing, heh. I *just* ran into this myself when working on an iOS app that integrates btleplug. Good news is, it was an easy fix, as 80% of the event handlers and callbacks were already there, just needed glue code to integrate it with the rest of the library.

v0.10.1 will be out with a fix this week.
