### ISSUE TITLE
Access the name of a peripheral

### ISSUE THREAD

**Issue by JosuGZ** [deviceplug/btleplug#263]
It would be nice to be able to access the name of a peripheral, I think it is not currently possible. Something like this:

![image](https://user-images.githubusercontent.com/25986871/190379534-a499eac8-5318-4f81-875b-1d6bb3d03608.png)

**Comment by qwandor** [comment]
You should be able to use `Peripheral::properties` to get a `PeripheralProperties`, then look in the `local_name` field.

**Comment by qdot** [comment]
Yup. You can just get it through the properties. Closing.
