### ISSUE TITLE
Derive Serde Serialize/Deserialize for All Types

### ISSUE THREAD

**Issue by IamfromSpace** [deviceplug/btleplug#27]
**Feature Description**

I'm working on an app right now that both displays notifications live and then records them for later processing.  Since I'm recording multiple characteristics, I need serialize-able tags to capture along with the notification value, and what better way than the `UUID` itself.

The `UUID` is a fairly trivial enum, so just creating an `SUUID` with `From` and `Serialize` implementations in my application solves my immediate needs.  However, it would simplify things and potentially be useful to others if this (and all or most other types) were Serializable as well.

I'm happy to contribute this feature (since it's more of a chore than anything else), if it seems like something worth adding!

**Comment by qdot** [comment]
Came in with 0.4.2
