### ISSUE TITLE
Impl FnMut for NotificationHandler to Enable Stateful Behaviors

### ISSUE THREAD

**Issue by IamfromSpace** [deviceplug/btleplug#28]
**Feature Description**

Currently, NotificationHandler implement `Fn`, which allows user to pass in a closure.  This closure may have captured it's environment via `move`, however, this is a read-only capture.  If NotificationHandler was `FnMut`, it could modify variables it captured as well.

For example, this becomes possible:

```rust
let mut i = 1;
my_peripheral.on_notification(Box::new(move |n| {
  println!("This is notification number {:?}: {:?}", i, n);
  i += 1;
}
```

This can be especially useful in places where characteristics require two points in time to give meaningful data (ex. cycling cadence).  So the previous can be constantly captured and updated, to be compared against the new incoming notification.

I've got a pull request incoming for this :)

**Comment by qdot** [comment]
Closing, as this was merged in March. But notifications will follow event handlers to being channels soon.
