### ISSUE TITLE
Add Class of device property

### ISSUE THREAD

**Issue by GreenDjango** [deviceplug/btleplug#284]
**Class of device**

Hi,

Is it possible to add class of device ([CoD](https://www.ampedrftech.com/datasheets/cod_definition.pdf)) property to `PeripheralProperties` struct?
I Just add this property to [bluez-async](https://github.com/bluez-rs/bluez-async) lib but I don't know if the other platforms can achieve that.

Thanks

**Comment by kristensala** [comment]
Changes merged to dev https://github.com/deviceplug/btleplug/pull/319
