### ISSUE TITLE
Are there any plans to add NimBLE support?

### ISSUE THREAD

**Issue by AnderssonPeter** [deviceplug/btleplug#309]
**Feature Description**

It would be nice if you added support for NimBLE that would make this library compatible with esp32 and other microcontrollers.

**Comment by qdot** [comment]
This is a host side desktop/mobile library. We have no plans on porting to embedded.

**Comment by AnderssonPeter** [comment]
Guess it would be too good to be true, if we could use the same library across both Mobile, Desktop and microcontrollers.
But thanks for taking the time to answer!
