### ISSUE TITLE
mac os: Discover MAC address	

### ISSUE THREAD

**Issue by gitmalong** [deviceplug/btleplug#320]
Hi!

I have not found a tracking issue for this feature so I am creating this one. Is that something that will be supported soon?

Thanks

**Comment by qdot** [comment]
This isn't possible. macOS hides it from the APIs.

**Comment by gitmalong** [comment]
How is it being done on https://github.com/toy/blueutil ? Might there be a private API?

**Comment by apertureless** [comment]
> How is it being done on [toy/blueutil](https://github.com/toy/blueutil) (which does not work on my machine with MacOS 13)? Might there be a private API?

As far as I rememeber, it was available in older macos versions but got removed at some point.
