### ISSUE TITLE
Resume Notifications On Reconnect

### ISSUE THREAD

**Issue by IamfromSpace** [deviceplug/btleplug#34]
**Feature Description**

If a connection drops, and I want to reconnect, likely I want to put the device right back into its previous state--including subscriptions and notification handlers.

At the moment, doing this is possible, but quite a bit of work.  All notification handlers have to be re-added (which may be non-trivial to setup), and each characteristic needs a re-subscription.  Encapsulating the state of what should happen on reconnect also poses some challenge.

To do something like this, I think there's two distinct steps:
  - Have the Peripherals be the keepers of the notification handlers (PR incoming, have linux working)
  - Track all subscribed characteristics in the peripherals, and immediately setup notify on each when connecting.

In the first step, users must only resubscribe, and in the second step just a re-connect is sufficient to continue receiving notifications.

The only drawback I see to this feature is that there's now no way to force a reset (in case users are doing this with disconnect+connect).  So that behavior (if used) is broken, and likely an explicit "reset" is required that clears all subscriptions and handlers.

**Comment by qdot** [comment]
Came in with v0.4.2.
