### ISSUE TITLE
BLE advertisements.

### ISSUE THREAD

**Issue by Frostie314159** [deviceplug/btleplug#342]
**Feature Description**

It would be helpful to register ble advertisements along with manufacturer data, since this is a feature supported by all platforms.

**Comment by qdot** [comment]
Can you provide more context here? I'm not sure what you're asking for.

**Comment by Frostie314159** [comment]
BLE allows you to advertise services. These can contain manufacturer data. As every platform supports sending BLE advertisements, I thought it would only make sense, if this crate exposed them as well.

**Comment by qdot** [comment]
We already handle that, it's on the peripheral properties struct, as `manufacturer_data`.

**Comment by Frostie314159** [comment]
Thx

**Comment by Frostie314159** [comment]
I can't seem to find a way to advertise a service. The peripheral properties struct only handles receiving advertisements.

**Comment by qdot** [comment]
That's out of the scope of this library. As the readme says, this is a host/central only library.
