### ISSUE TITLE
State of Maintenance

### ISSUE THREAD

**Issue by newcomertv** [deviceplug/btleplug#373]
First things first. Thanks for the effort put into this library. 
FOSS is mostly driven by volunteer work and this repository is no different.

It appears to be a promising cross-platform solution that would bring the embedded world one step closer to sharing application code with the app side.

I'd like to inquire about the  current state of Maintenance of this lib?

Looking at the version/commit history it appears the library is feature complete.
Exception : A web API PR exists which has seemingly been abandoned (apparent reason: no tokio in wasm)

Various issues appear to regularly get solved but never closed.
This is worrying as they almost exclusively have a bug label.

Can this library be considered reliable and maintained (production ready) or would consuming this library imply having to perpetually maintain a dependency?

**Comment by qdot** [comment]
This is an open source library and therefore comes with the normal trappings of open source.

If you are interested in a production ready system with ongoing support, I am happy to discuss licensing and contract terms.

**Comment by qdot** [comment]
I use this library bound to flutter to ship an app with 20k+ installs across desktop and mobile (almost a 50/50 split at this point). Mobile has issues but it generally works.

There's been discussions about a react native binding but I'm not sure if that's gone anywhere yet.
