### ISSUE TITLE
Stop using failure as a library error type

### ISSUE THREAD

**Issue by qdot** [deviceplug/btleplug#48]
**Describe the bug**
Switch from using failure to using thiserror, so the library doesn't leak types.

**Comment by blandger** [comment]
I've tried github.com/shepmaster/snafu . As I see it's quite similar to thiserror. That doesn't matter for me which one can be used. I'm just curious about 'selection criterias'.

**Comment by qdot** [comment]
I use thiserror over in buttplug-rs. It's a thinner layer on top of errors than snafu, just kinda felt better to me (not to mention I use color-eyre at the binary level which snaps in nicely). Snafu is also a fine library though, shepmaster does good work. Mostly a personal pref thing.

**Comment by qdot** [comment]
Fixed in #108
