### ISSUE TITLE
Implement Debug for various types

### ISSUE THREAD

**Issue by MattesWhite** [deviceplug/btleplug#50]
Many management types of `btleplug` lack implementations of the `Debug` trait, e.g. `ConnectedAdapter`. This makes it inconvenience to develop a Bluetooth application as I can't simply `#[derive(Debug)]` on my state-`struct`.  The implementation is not required to include detailed information something like `ConnectedAdapter(hci0)` would be totally sufficient.

**Comment by qdot** [comment]
I'm gonna be working on replacing the event system this weekend, will see what I can do about getting this done too.

**Comment by qdot** [comment]
Ok, well, got ConnectedAdapter at least, so I'll close this for now and open another followup for other platforms (CoreBluetooth and UWP have some opaque type issues I need to figure out).
