### ISSUE TITLE
Move CI to Github Actions

### ISSUE THREAD

**Issue by qdot** [deviceplug/btleplug#65]
Set up CI on Azure Pipelines on #16, but tried Github Actions and it was really nice. Would like to move CI in-repo using GAs.

I should've listened to @mfiumara in the first place. :)

**Comment by mfiumara** [comment]
I have also been impressed with GA and it keeps getting more support. You could re-open #37 for an initial skeleton

**Comment by archseer** [comment]
actions-rs is unofficial but widely used: https://github.com/actions-rs/example

**Comment by qdot** [comment]
Ok well I have swung back to Azure Pipelines after some real nightmarish GA build times so we'll leave this as is for now.
