### ISSUE TITLE
Device lost on failed connection

### ISSUE THREAD

**Issue by MattesWhite** [deviceplug/btleplug#78]
**Describe the bug**

Some times it fails to connect to a device. I think this is just Bluetooth itself and has nothing to do with this crate. However, when this happens the newest version of `btleplug` seems to drop the respective peripheral. Accordingly, the peripheral does not appear in `Central::peripherals()` which means one has to wait until the device is rediscovered before the next try to connect. This leads to confusing errors.

**Expected behavior**

The `Central` does not drop devices when they fail to connect. The manufacturer data and other information could still be useful.

**Actual behavior**

The `Central` unnecessarily drops the device from its peripheral list. Users have to wait for the next re-discovery.

**Additional context**

Running Raspbian on a Raspberry Pi 3, i.e. I use bluerz.

Example log:

```
Sep 08 11:59:42.296 DEBUG btleplug::bluez::adapter::peripheral: created socket 32 to communicate with device    
Sep 08 11:59:42.296 DEBUG btleplug::bluez::adapter::peripheral: bound to socket 32    
Sep 08 11:59:42.296 DEBUG btleplug::bluez::adapter::peripheral: configured socket 32    
Sep 08 11:59:42.349  INFO btleplug::bluez::adapter: connected to LEConnInfo { handle: 64, role: 0, bdaddr: FF:FF:80:01:C9:C4, bdaddr_type: 0, interval: 39, latency: 0, supervision_timeout: 42, master_clock_accuracy: 0 }    
Sep 08 11:59:42.349 DEBUG btleplug::bluez::adapter::peripheral: got le conn complete LEConnInfo { handle: 64, role: 0, bdaddr: FF:FF:80:01:C9:C4, bdaddr_type: 0, interval: 39, latency: 0, supervision_timeout: 42, master_clock_accuracy: 0 }    
Sep 08 11:59:42.679 DEBUG btleplug::bluez::util: got error ENOSYS: Function not implemented    
Sep 08 11:59:42.680 DEBUG btleplug::bluez::adapter::peripheral: Failed to connect (ENOSYS: Function not implemented), closing socket 32    
Sep 08 11:59:42.718 DEBUG btleplug::bluez::adapter::peripheral: removing stream for FF:FF:80:01:C9:C4 due to disconnect    
```

**Comment by qdot** [comment]
We've completely reworked how we handle our peripheral handling since this bug was filed, so I'm gonna close this with the *assumption* that things work, but I may be completely wrong there since I don't have an easy STR to follow to test. Please feel free to reopen or refile if this is still happening.
