### ISSUE TITLE
`unwrap` fails on `None` when trying to write/subscribe to a characteristic (MacOS/CoreBluetooth)

### ISSUE THREAD

**Issue by MacTuitui** [deviceplug/btleplug#99]
**Describe the bug**
I'm trying to write (or subscribe) to a characteristic but I'm getting an error (with CoreBluetooth). 
 
**Expected behavior**
To write to the characteristic, or having the error tell me more.

**Actual behavior**
I'm using the basic "lights" example (modified to my device UUID), but the `command()` calls fails on https://github.com/deviceplug/btleplug/blob/master/src/corebluetooth/internal.rs#L379
If I try to subscribe to a characteristic, it fails on 
https://github.com/deviceplug/btleplug/blob/master/src/corebluetooth/internal.rs#L324
that seems to be very similar in terms of logic.

I can connect to the device (it beeps as it should), I can retrieve the list of characteristics (so communication works), so the basics are there, I'm just one step away from having everything working!

**Additional context**
MacBook Pro16", 2019
Catalina 10.15.7

**Comment by qdot** [comment]
macOS/CoreBluetooth got a big ol' rewrite in v0.8, so I think we've fixed this. If not, feel free to refile.
